//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadPlayVideoFile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestingDBEntities : DbContext
    {
        public TestingDBEntities()
            : base("name=TestingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MediaFile> MediaFiles { get; set; }
    
        public virtual ObjectResult<GetMediaFiles_Result> GetMediaFiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMediaFiles_Result>("GetMediaFiles");
        }
    
        public virtual int SaveMediaFile(string filename, Nullable<int> filesize, string filepath)
        {
            var filenameParameter = filename != null ?
                new ObjectParameter("filename", filename) :
                new ObjectParameter("filename", typeof(string));
    
            var filesizeParameter = filesize.HasValue ?
                new ObjectParameter("filesize", filesize) :
                new ObjectParameter("filesize", typeof(int));
    
            var filepathParameter = filepath != null ?
                new ObjectParameter("filepath", filepath) :
                new ObjectParameter("filepath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveMediaFile", filenameParameter, filesizeParameter, filepathParameter);
        }
    }
}
